### ISSUE TITLE
nonce error

### ISSUE THREAD

**Issue by iamchenchen** [dreimannzelt/layer-token_service#2]
for example: nonce = Tg6MMWXkkV8JqqyHspII+/9p0WzIcnhnGfusTs9qvF0Ff3GuEELvucCYiri7lKKR8rpdVrywKbvniORY3ffGxg==

the +/ will become space when validate.

**Comment by we5** [comment]
Sorry for the late reply. I did not have time to investigate that further as we never had any problems with any nonce we used so far.

@benedikt did you have any problems or do you see any?

**Comment by iamchenchen** [comment]
@we5 I've switched to native code.  And I've also verified with Layer team, this is a bug. However, thank you for your support, I did learn a lot from you code.

**Comment by we5** [comment]
@iamchenchen You mean this is a bug in our service or with Layer?

**Comment by benedikt** [comment]
@iamchenchen How did you submit the nonce to the server? As JSON body or as a query parameter?
